# Generated by Django 5.2 on 2025-10-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone_number',
            field=models.SmallIntegerField(),
        ),
    ]
