# Generated by Django 5.2 on 2025-10-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0002_alter_manager_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='category',
            field=models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Risk', 'Risk')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='subcategory',
            field=models.CharField(max_length=100),
        ),
    ]
