# Generated by Django 5.2 on 2025-10-06 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0003_reportcontent_entry_alter_reportcontent_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='weekly_report',
            old_name='lock_status',
            new_name='is_locked',
        ),
        migrations.RemoveField(
            model_name='reportcontent',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='submissiondeadline',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='submissiondeadline',
            name='due_time',
        ),
        migrations.RemoveField(
            model_name='submissiondeadline',
            name='extended_date',
        ),
        migrations.RemoveField(
            model_name='submissiondeadline',
            name='extended_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='Enter text'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissiondeadline',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissiondeadline',
            name='extended_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='reporting_app.manager'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='category',
            field=models.CharField(choices=[('Green', 'Green'), ('Amber', 'Amber'), ('Risk', 'Risk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='weekly_report',
            index=models.Index(fields=['status', 'created_at'], name='reporting_a_status_a997d7_idx'),
        ),
    ]
