# Generated by Django 5.2 on 2025-10-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0004_rename_departments_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
