# Generated by Django 5.2 on 2025-10-15 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0005_reportcontent_manager_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='assigned_projects',
            field=models.ManyToManyField(blank=True, related_name='assigned_supervisors', to='reporting_app.project'),
        ),
        migrations.AddField(
            model_name='weekly_report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='reporting_app.project'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='supervisor',
            field=models.ManyToManyField(blank=True, to='reporting_app.supervisor'),
        ),
    ]
