# Generated by Django 5.2 on 2025-10-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0006_supervisor_assigned_projects_weekly_report_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_report',
            name='project',
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='reporting_app.project'),
        ),
    ]
