# Generated by Django 5.2 on 2025-10-28 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0007_remove_weekly_report_project_reportcontent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_report',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporting_app.project'),
        ),
    ]
