# Generated by Django 5.2 on 2025-11-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0009_alter_weekly_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_report',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Rework', 'Rework'), ('Approved', 'Approved'), ('Waived', 'Waived')], default='Draft', max_length=20),
        ),
    ]
