# Generated by Django 5.2 on 2025-11-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0010_alter_weekly_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_report',
            name='supervisor_task',
            field=models.TextField(blank=True, help_text="Briefly describe the supervisor's task for this project cycle.", null=True, verbose_name='Project Task'),
        ),
    ]
