# Generated by Django 5.2 on 2025-11-14 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0011_weekly_report_supervisor_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_report',
            name='supervisor_task',
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField(help_text='The specific task assigned for this project cycle.', verbose_name='Task Description')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='reporting_app.weekly_report')),
            ],
        ),
    ]
