# Generated by Django 5.2 on 2025-11-14 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0012_remove_weekly_report_supervisor_task_projecttask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
