# Generated by Django 5.2.10 on 2026-02-04 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0014_dailyreport_dailyreportcontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Weekly_Report',
            new_name='WeeklyReport',
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'permissions': [('view_all_daily_reports', 'Can view all daily reports')]},
        ),
        migrations.AlterModelOptions(
            name='weeklyreport',
            options={'permissions': [('view_all_weekly_reports', 'Can view all weekly reports'), ('review_weekly_reports', 'Can review weekly reports')]},
        ),
        migrations.RemoveIndex(
            model_name='weeklyreport',
            name='reporting_a_status_a997d7_idx',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='user',
        ),
        migrations.AlterField(
            model_name='manager',
            name='supervisor',
            field=models.ManyToManyField(blank=True, related_name='managers', to='reporting_app.supervisor'),
        ),
        migrations.AlterField(
            model_name='reportcontent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_contents', to='reporting_app.project'),
        ),
        migrations.AddField(
            model_name='admin',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='reporting_app.department'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to='reporting_app.admin'),
        ),
    ]
