# Generated by Django 5.2.10 on 2026-02-04 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0015_admin_rename_weekly_report_weeklyreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Approved', 'Approved'), ('Waived', 'Waived')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='weeklyreport',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected'), ('Rework', 'Rework'), ('Approved', 'Approved'), ('Waived', 'Waived')], default='Draft', max_length=20),
        ),
        migrations.CreateModel(
            name='DailyReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='Enter text')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_comments', to='reporting_app.manager')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reporting_app.dailyreport')),
            ],
        ),
        migrations.CreateModel(
            name='DailyReportSupervisorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(default='Enter text')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_comments', to='reporting_app.dailyreport')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report_comments', to='reporting_app.supervisor')),
            ],
        ),
    ]
