# Generated by Django 5.2.10 on 2026-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0017_extensionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailyreportcontent',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reportcontent',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
