# Generated by Django 5.2.10 on 2026-02-04 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0018_dailyreport_project_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
