# Generated by Django 5.2.10 on 2026-02-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting_app', '0019_dailyreport_status_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='submissiondeadline',
            name='due_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submissiondeadline',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='reporting_app.supervisor'),
        ),
        migrations.AddField(
            model_name='submissiondeadline',
            name='reporting_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='reporting_app.reportingweek'),
        ),
    ]
